name: Build and push docker image

on:
    push:
        branches:
            - docker-images

permissions: write-all

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Set lower case owner name
              run: |
                  echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
              env:
                  OWNER: "${{ github.repository_owner }}"
            - name: Set lower case repo name
              run: |
                  echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
              env:
                  REPO: "${{ github.event.repository.name }}"
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push db image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: Dockerfile.db
                  push: true
                  tags: ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}/db:latest,ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}/db:${{github.sha}}

            - name: Build and push seller image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: Dockerfile.seller
                  push: true
                  tags: ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}/seller:latest,ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}/seller:${{github.sha}}
